### ISSUE TITLE
Fix switch label paddings

### ISSUE THREAD

**Issue by troyqa** [PeculiarVentures/peculiar-react-components#106]
There's padding difference at switch label between current `Peculiar React Components` and Hancock mockup.

<details>

<summary>current</summary>

<img width="453" alt="Screenshot 2022-08-22 at 14 47 52" src="https://user-images.githubusercontent.com/37020930/185914443-9d9c52ff-29a9-41cf-80ab-c8572699d01c.png">

</details>

<details>

<summary>mockup</summary>

<img width="761" alt="Screenshot 2022-08-22 at 14 51 16" src="https://user-images.githubusercontent.com/37020930/185914853-2c066ecc-8c35-4aea-875b-fb3e83b89eb7.png">

</details>

My suggestion is to change `padding-left` and `padding-right` from `20px` to `10px` at `switch_label` position left/right.

I have analyzed and found no situations where it could affect other components

**Comment by WorldThirteen** [comment]
I don't think it safe to make such a global update, since these components might be used for different projects.
I'd like to recommend fix it in place for your issue and your project. This library is a public project with a kind of design system, so it should not fit some specific mockup of your project.

So I'd like to close this issue as not planned. cc @donskov.

**Comment by donskov** [comment]
You are right @WorldThirteen. I also don't want to make these changes now because of the threat of breaking something in other projects.

Close!
